apiVersion: v1
kind: Service
metadata:
  name: app-lb-svc
  labels:
    app: app-lb-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: app-deploy
