version: "3.8"

services:
  database:
    build: 
      context: ./app/database
    image: williamlima/project-database:1.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: dataset
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build:
      context: ./app/backend
    image: williamlima/project-backend:1.0
    container_name: php_backend
    ports:
      - "80:80"
    depends_on:
      - database
    networks:
      - app_network
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: dataset
      DB_USER: root
      DB_PASSWORD: Senha123
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
