apiVersion: v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: fileserver-httpd
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: fileserver-httpd
          persistentVolumeClaim:
            claimName: fileserver-httpd
